name: AWS Lambda CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'



  deploy-and-test:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'  # Change to your AWS region
      - name: Build with Maven
        run: mvn clean test
        
      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code --function-name HandlerString --zip-file fileb://target/aws_usecase-1.0-SNAPSHOT.jar

      - name: Run Lambda Test
        run: |
          aws lambda invoke --function-name Dogbreedlambda --log-type Tail /dev/null | jq '.LogResult' -r | base64 --decode
